apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcs-controller
  namespace: karmada-system
  labels:
    app: mcs-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcs-controller
  template:
    metadata:
      labels:
        app: mcs-controller
    spec:
      automountServiceAccountToken: false
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      containers:
        - name: mcs-controller
          image: karmada/mcs-controller:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/mcs-controller
            - --kubeconfig=/etc/kubeconfig
            - --bind-address=0.0.0.0
            - --secure-port=10357
            - --v=4
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10357
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
          - name: kubeconfig
            subPath: kubeconfig
            mountPath: /etc/kubeconfig
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
